# main links
main:
  - title: DataBase
    url: /categories/database/
  - title: Web
    url: /categories/Web/
  - title: Algorithms
    url: /categories/algorithms/
  - title: Operating System
    url: /categories/operating_system/
  - title: Java
    url: /categories/java/
  - title: Spring
    url: /categories/spring/
#   - title: Github
#     url: /categories/programming/
# - title: "Sitemap"
#   url: /sitemap/
# - title: "Quick-Start Guide"
#   url: https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

database:
  - title: "데이터베이스와 데이터베이스 관리 시스템의 개념"
    children:
      - title: "데이터베이스의 기본 개념"
        url: /database/lesson01
      - title: "데이터베이스 관리 시스템"
        url: /database/lesson02
      - title: "데이터베이스 시스템"
        url: /database/lesson03

spring:
  - title: "스프링"
    children:
      - title: "스프링 개념잡기"
        url: /spring/lesson01
      - title: "JPA 개념잡기"
        url: /spring/lesson02
      - title: Spring Boot 동작원리"
        url: /spring/lesson03
# docs:
#   - title: Computer Science
#     children:
#       - title: "DataBase"
#         url: /database/basic_concept
#       - title: "NetWork"
#         url: /docs/network/
#       - title: "Algorithms"
#         url: /docs/algorithms/

#   - title: Programming
#     children:
#       - title: "Java"
#         url: /docs/configuration/
#       - title: "Spring"
#         url: /docs/navigation/

#   - title: Extras
#     children:
#       - title: "Etc"
#         url: /docs/configuration/

